/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITProject;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Azmol-IT
 */
public class AdminstrationFrame extends javax.swing.JFrame {

    DatabaseConnection dbObj = new DatabaseConnection();
    SwingComponentAccess component = new SwingComponentAccess();
    Connection con = dbObj.doConnection();
    PreparedStatement pstm = null;
    
    private String strSchCourseCode, strSchRound, strMonthExam,
            strSchType, strSChDate, strSchTime;
    private Date schTime;
    
    private String strRegStuId, strRegStuName,strRegSutFN,
            strStuSub, strStuHD, strStuRound;
    private  String[] strDegree = new String[5];
    private int regID;
    private String strRegConsId, strRegConsName,strConsSub, strConsFarm, 
            strConsEmail, strConsPhone;
    private String strRegTSPId, strRegTSPName,strTSPLocation, strNoLab, 
            strTSPStuCap, strTSPNoTeacher;
    private  String[] sub = new String[7];
    private int lab,stuCap,teacher;
    private String imagePath;
    
    /**
     * Creates new form AdminstrationFrame
     */
    public AdminstrationFrame() {
        initComponents();
        openingWindow();
    }
    
    public void windowConfig(){
        Toolkit theKit = this.getToolkit();
        Dimension winSize = theKit.getScreenSize();
        this.setLocation(winSize.width/28, winSize.height/20);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../image/icon.png")));
    }
    
    public void openingWindow(){
        windowConfig();
        initialComboBox();
        studentRegIdRetrive();
        component.courseCodeRetriveAdmin(cbxAdminSchCourseCode, cbxAdminSchRound);
        component.courseCodeRetriveAdmin(cbxRegCons);
    }
    
    public void initialComboBox(){
        cbxAdminSchCourseCode.addItem("Select");
        cbxAdminSchRound.addItem("Select");
        cbxRegCons.addItem("Select");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelDynamicReg = new javax.swing.JPanel();
        panelStudent = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        ba = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxRegSubject = new javax.swing.JComboBox();
        bba = new javax.swing.JCheckBox();
        txtRegStudentFN = new javax.swing.JTextField();
        cbxRegHD = new javax.swing.JComboBox();
        mba = new javax.swing.JCheckBox();
        cbxRegAppRound = new javax.swing.JComboBox();
        bsc = new javax.swing.JCheckBox();
        txtRegStudentName = new javax.swing.JTextField();
        msc = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtRegStudentId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStuRegImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        panelCons = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtConsName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxRegCons = new javax.swing.JComboBox();
        txtConsFarm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtConsId = new javax.swing.JTextField();
        txtConsEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtConsPhone = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        panelTSP = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtTSPName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jee = new javax.swing.JCheckBox();
        gave = new javax.swing.JCheckBox();
        accd = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        txtTSPStuCap = new javax.swing.JTextField();
        txtTSPLocation = new javax.swing.JTextField();
        wpsi = new javax.swing.JCheckBox();
        ddd = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        nt = new javax.swing.JCheckBox();
        cSharp = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTSPId = new javax.swing.JTextField();
        txtTSPNoLab = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTSPNoTeacher = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbxAdminSchCourseCode = new javax.swing.JComboBox();
        cbxAdminSchType = new javax.swing.JComboBox();
        cbxAdminSchRound = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        dcSchDate = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        txtAdminSchMonth = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdminSch = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IT Scholarship Project");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        jPanel7.setLayout(new java.awt.GridLayout(7, 1, 12, 12));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Student Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Consultant Registration");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("TSP Registration");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        panelDynamicReg.setLayout(new java.awt.CardLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Registration Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        ba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ba.setText("BA");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Student Name : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Home Distrct : ");

        cbxRegSubject.setEditable(true);
        cbxRegSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRegSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mathematics", "Bangla", "English", "Madrasha", "Diploma" }));

        bba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bba.setText("BBA");

        txtRegStudentFN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbxRegHD.setEditable(true);
        cbxRegHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRegHD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Dhaka", "Jessore", "CTG", "Khulna" }));

        mba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mba.setText("MBA");

        cbxRegAppRound.setEditable(true);
        cbxRegAppRound.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRegAppRound.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Round - 31", "Round - 32" }));

        bsc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bsc.setText("B.Sc");

        txtRegStudentName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        msc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        msc.setText("M.Sc");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Applied Round : ");

        txtRegStudentId.setEditable(false);
        txtRegStudentId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Father Name : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Subject : ");

        lblStuRegImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStuRegImage.setText("jLabel8");
        lblStuRegImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Degree : ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Student ID : ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRegStudentId)
                        .addComponent(txtRegStudentName)
                        .addComponent(txtRegStudentFN, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxRegAppRound, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxRegHD, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxRegSubject, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(bsc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(msc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mba)
                                .addGap(0, 32, Short.MAX_VALUE)))
                        .addGap(51, 51, 51)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblStuRegImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblStuRegImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtRegStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtRegStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtRegStudentFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bsc)
                                    .addComponent(bba)
                                    .addComponent(ba)
                                    .addComponent(msc)
                                    .addComponent(mba)))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5))
                        .addComponent(cbxRegSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbxRegHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxRegAppRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Registration");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelDynamicReg.add(panelStudent, "card2");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultant Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Consulting Fram: ");

        txtConsName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Consultant ID : ");

        cbxRegCons.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtConsFarm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Required Course : ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Contact : ");

        txtConsId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtConsEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Consultant Name : ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Email : ");

        txtConsPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConsId)
                    .addComponent(txtConsName)
                    .addComponent(cbxRegCons, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtConsFarm)
                    .addComponent(txtConsEmail)
                    .addComponent(txtConsPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtConsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtConsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addComponent(cbxRegCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtConsFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(txtConsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(txtConsPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Registration");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelConsLayout = new javax.swing.GroupLayout(panelCons);
        panelCons.setLayout(panelConsLayout);
        panelConsLayout.setHorizontalGroup(
            panelConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        panelConsLayout.setVerticalGroup(
            panelConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDynamicReg.add(panelCons, "card3");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TSP Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel18.setText("No. of  Lab : ");

        jLabel21.setText("Avilable Course : ");

        jee.setText("J2EE");

        gave.setText("GAVE");

        accd.setText("Autocard");

        jLabel16.setText("TSP Name : ");

        wpsi.setText("WPSI");

        ddd.setText("DDD");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Registration");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        nt.setText("Networking");

        cSharp.setText("C#");

        jLabel19.setText("Student Capacity : ");

        jLabel15.setText("TSP Code : ");

        jLabel20.setText("No. of Teacher : ");

        jLabel17.setText("Location : ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTSPId)
                            .addComponent(txtTSPName)
                            .addComponent(txtTSPLocation)
                            .addComponent(txtTSPNoLab)
                            .addComponent(txtTSPStuCap)
                            .addComponent(txtTSPNoTeacher)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSharp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ddd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wpsi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accd))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTSPId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTSPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTSPLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTSPNoLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTSPStuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTSPNoTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jee)
                    .addComponent(ddd)
                    .addComponent(cSharp)
                    .addComponent(wpsi)
                    .addComponent(gave)
                    .addComponent(nt)
                    .addComponent(accd))
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTSPLayout = new javax.swing.GroupLayout(panelTSP);
        panelTSP.setLayout(panelTSPLayout);
        panelTSPLayout.setHorizontalGroup(
            panelTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTSPLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        panelTSPLayout.setVerticalGroup(
            panelTSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTSPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        panelDynamicReg.add(panelTSP, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(panelDynamicReg, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDynamicReg, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registration", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schedule Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel23.setText("Date : ");

        cbxAdminSchCourseCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAdminSchCourseCodeItemStateChanged(evt);
            }
        });

        cbxAdminSchType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Feedback", "External Exam", "Evidance Exam" }));

        cbxAdminSchRound.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAdminSchRoundItemStateChanged(evt);
            }
        });

        jLabel25.setText("Round : ");

        dcSchDate.setDateFormatString("yyyy-MM-dd");

        jLabel22.setText("Schdule Type : ");

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Add Schedule");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        txtAdminSchMonth.setEditable(false);

        jLabel27.setText("No. of Monthly Exam : ");

        jLabel26.setText("Course Code : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxAdminSchRound, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAdminSchMonth)
                            .addComponent(cbxAdminSchType, 0, 140, Short.MAX_VALUE)
                            .addComponent(dcSchDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxAdminSchCourseCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cbxAdminSchCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cbxAdminSchRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtAdminSchMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(cbxAdminSchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel23))
                    .addComponent(dcSchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        tableAdminSch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAdminSch.setRowHeight(25);
        jScrollPane1.setViewportView(tableAdminSch);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Schedule", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // removing panel
        panelDynamicReg.removeAll();
        panelDynamicReg.repaint();
        panelDynamicReg.revalidate();
        
        // adding panel
        panelDynamicReg.add(panelStudent);
        panelDynamicReg.repaint();
        panelDynamicReg.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // removing panel
        panelDynamicReg.removeAll();
        panelDynamicReg.repaint();
        panelDynamicReg.revalidate();
        
        // adding panel
        panelDynamicReg.add(panelCons);
        panelDynamicReg.repaint();
        panelDynamicReg.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // removing panel
        panelDynamicReg.removeAll();
        panelDynamicReg.repaint();
        panelDynamicReg.revalidate();
        
        // adding panel
        panelDynamicReg.add(panelTSP);
        panelDynamicReg.repaint();
        panelDynamicReg.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        LoginFrame loginMain = new LoginFrame();
        loginMain.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void cbxAdminSchCourseCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAdminSchCourseCodeItemStateChanged
        // TODO add your handling code here:
        component.jCOmboBoxRemove2ndItem(cbxAdminSchRound);
        component.roundRetriveByCourse(cbxAdminSchCourseCode, cbxAdminSchRound);
    }//GEN-LAST:event_cbxAdminSchCourseCodeItemStateChanged

    private void cbxAdminSchRoundItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAdminSchRoundItemStateChanged
        // TODO add your handling code here:
        component.resetTextField(cbxAdminSchRound, txtAdminSchMonth);
        monthExam();
    }//GEN-LAST:event_cbxAdminSchRoundItemStateChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        updateSchdule();
        String stm = "Select course_code, round, exam_month, schdule_type, sch_date from schdule_info";
        component.tableDataRetrive(stm, tableAdminSch);
        schduleInitialValues();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        insertingRegStu();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        insertingRegCons();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        insertingRegTsp();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        imagePath = component.getImage(lblStuRegImage);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminstrationFrame().setVisible(true);
            }
        });
    }
    
    public void schduleInitialValues(){
        try {
            strSchCourseCode = cbxAdminSchCourseCode.getSelectedItem().toString();
            strSchRound = cbxAdminSchRound.getSelectedItem().toString();
            strMonthExam = txtAdminSchMonth.getText();
            strSchType = cbxAdminSchType.getSelectedItem().toString();
            strSChDate = ((JTextField) dcSchDate.getDateEditor().getUiComponent()).getText().toString();
//            System.out.println("problem1");
//            strSchTime = spinnerSchTime.getValue().toString();
//            System.out.println("problem2");
            System.out.println("Time : " + strSchTime);
        } catch (Exception e) {
            System.out.println("problem");
        }
    }
    
    public void monthExam(){
        ResultSet rs = null;
        String stm = "select max(rt.noOfMonth) as 'Month'\n" +
                    "from result_table rt, student_table st, batch_info bi\n" +
                    "where rt.student_id = st.student_id\n" +
                    "and st.batch_id = bi.batch_id\n" +
                    "and bi.course_code ='"+cbxAdminSchCourseCode.getSelectedItem().toString()+"'\n" +
                    "and bi.round = '"+cbxAdminSchRound.getSelectedItem().toString()+"'";
        try {
            pstm = con.prepareStatement(stm);
            rs = pstm.executeQuery();
            if(rs.next()){
                txtAdminSchMonth.setText(String.valueOf(rs.getInt(1)+1));
            }else{
                txtAdminSchMonth.setText("1");
            }
        } catch (Exception e) {
        }
    }
    
    public void updateSchdule(){
        schduleInitialValues();
        String stm = "insert into schdule_info(course_code, round, exam_month, schdule_type, sch_date) "
                + "values('"+strSchCourseCode+"','"+strSchRound+
                "','"+strMonthExam+"','"+strSchType+"','"+strSChDate+"')";
        try {
            pstm = con.prepareStatement(stm);
            int n = pstm.executeUpdate();
            if (n>0) {
                System.out.println("insert Data");
            } else {
                System.out.println("not insert Data");
            }
        } catch (Exception e) {
        }
//        component
    }
    
    public void studentRegIdRetrive(){
        ResultSet rs = null;
        String stm = "select max(stu_id)+1 from student_info;";
        try {
            pstm = con.prepareStatement(stm);
            rs = pstm.executeQuery();
            if (rs.next()) {
                txtRegStudentId.setText(String.valueOf(rs.getInt(1)));
            }
        } catch (Exception e) {
        }
    }
    
    public void initialStuReg(){
        
        try {
            strRegStuId = txtRegStudentId.getText();
            strRegStuName = txtRegStudentName.getText();
            strRegSutFN = txtRegStudentFN.getText();

            if (bsc.isSelected()) {
                strDegree[0] = "B.Sc";
            }
            if (ba.isSelected()) {
                strDegree[1] = "BA";
            }
            if (bba.isSelected()) {
                strDegree[2] = "BBA";
            }
            if (mba.isSelected()) {
                strDegree[3] = "MBA";
            }
            if (msc.isSelected()) {
                strDegree[4] = "M.Sc";
            }

            strStuSub = cbxRegSubject.getSelectedItem().toString();
            strStuHD = cbxRegHD.getSelectedItem().toString();
            strStuRound = cbxRegAppRound.getSelectedItem().toString();
            
            regID = Integer.parseInt(strRegStuId);
        } catch (Exception e) {
        }
    }
    
    public void insertingRegStu(){
        initialStuReg();
        int n =0;
        String stm = "insert into student_info values(?,?,?,?,?,?,?,?,?,?,?)";
        
        try {
            pstm = con.prepareStatement(stm);
            InputStream image = new FileInputStream(new File(imagePath));
            pstm.setInt(1, regID);
            pstm.setString(2, strRegStuName);
            pstm.setString(3, strRegSutFN);
            pstm.setString(4, strStuSub);
            pstm.setString(5, strStuHD);
            pstm.setString(6, strDegree[0]);
            pstm.setString(7, strDegree[1]);
            pstm.setString(8, strDegree[2]);
            pstm.setString(9, strDegree[3]);
            pstm.setString(10, strDegree[4]);
            pstm.setBlob(11, image);
            n = pstm.executeUpdate();
            if (n>0) {
                System.out.println("Student Regestred");
            } else {
                System.out.println("Student not Regestred");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminstrationFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminstrationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void initialConsReg(){
        
        try {
            strRegConsId = txtConsId.getText();
            strRegConsName = txtConsName.getText();
            strConsSub = cbxRegCons.getSelectedItem().toString();
            strConsFarm = txtConsFarm.getText();
            strConsEmail = txtConsEmail.getText();
            strConsPhone = txtConsPhone.getText();
        } catch (Exception e) {
        }
    }
    
    public void insertingRegCons(){
        initialConsReg();
        int n =0;
        String stm = "insert into consultant_info(cons_id, cons_name, consultIng_fram, email, contact, course1) values(?,?,?,?,?,?)";
        try {
            pstm = con.prepareStatement(stm);
            pstm.setString(1, strRegConsId);
            pstm.setString(2, strRegConsName);
            pstm.setString(3, strConsFarm);
            pstm.setString(4, strConsEmail);
            pstm.setString(5, strConsPhone);
            pstm.setString(6, strConsSub);
            n = pstm.executeUpdate();
            if (n>0) {
                System.out.println("Student Regestred");
            } else {
                System.out.println("Student not Regestred");
            }
        } catch (Exception e) {
        }
        
    }
    
    public void initialTSPRegValues(){
        {
            strRegTSPId = txtTSPId.getText();
            strRegTSPName = txtTSPName.getText();
            strTSPLocation = txtTSPLocation.getText();
            strNoLab = txtTSPNoLab.getText();
            strTSPStuCap = txtTSPStuCap.getText();
            strTSPNoTeacher = txtTSPNoTeacher.getText();
            
            lab = Integer.parseInt(strNoLab);
            stuCap = Integer.parseInt(strTSPStuCap);
            teacher = Integer.parseInt(strTSPNoTeacher);
            
            if (jee.isSelected()) {
                sub[0] = "J2EE";
            }
            if (cSharp.isSelected()) {
                sub[1] = "C#";
            }
            if (ddd.isSelected()) {
                sub[2] = "DDD";
            }
            if (wpsi.isSelected()) {
                sub[3] = "WPSI";
            }
            if (gave.isSelected()) {
                sub[4] = "GAVE";
            }
            if (nt.isSelected()) {
                sub[5] = "NT";
            }
            if (accd.isSelected()) {
                sub[6] = "ACAD";
            }
        } 
    }
    
    public void insertingRegTsp(){
        try {
            initialTSPRegValues();
            dbObj.doConnection();
            String stm = "insert into tsp_info values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pstm = con.prepareStatement(stm);
            pstm.setString(1, strRegTSPId);
            pstm.setString(2, strRegTSPName);
            pstm.setString(3, strTSPLocation);
            pstm.setInt(4, lab);
            pstm.setInt(5, stuCap);
            pstm.setInt(6, teacher);
            pstm.setString(7, sub[0]);
            pstm.setString(8, sub[1]);
            pstm.setString(9, sub[2]);
            pstm.setString(10, sub[3]);
            pstm.setString(11, sub[4]);
            pstm.setString(12, sub[5]);
            pstm.setString(13, sub[6]);
            
            int n = pstm.executeUpdate();
            if (n>0) {
                JOptionPane.showMessageDialog(null, "TSP Registred");
            } else {
                JOptionPane.showMessageDialog(null, "TSP not Registred");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminstrationFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox accd;
    private javax.swing.JCheckBox ba;
    private javax.swing.JCheckBox bba;
    private javax.swing.JCheckBox bsc;
    private javax.swing.JCheckBox cSharp;
    private javax.swing.JComboBox cbxAdminSchCourseCode;
    private javax.swing.JComboBox cbxAdminSchRound;
    private javax.swing.JComboBox cbxAdminSchType;
    private javax.swing.JComboBox cbxRegAppRound;
    private javax.swing.JComboBox cbxRegCons;
    private javax.swing.JComboBox cbxRegHD;
    private javax.swing.JComboBox cbxRegSubject;
    private com.toedter.calendar.JDateChooser dcSchDate;
    private javax.swing.JCheckBox ddd;
    private javax.swing.JCheckBox gave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jee;
    private javax.swing.JLabel lblStuRegImage;
    private javax.swing.JCheckBox mba;
    private javax.swing.JCheckBox msc;
    private javax.swing.JCheckBox nt;
    private javax.swing.JPanel panelCons;
    private javax.swing.JPanel panelDynamicReg;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel panelTSP;
    private javax.swing.JTable tableAdminSch;
    private javax.swing.JTextField txtAdminSchMonth;
    private javax.swing.JTextField txtConsEmail;
    private javax.swing.JTextField txtConsFarm;
    private javax.swing.JTextField txtConsId;
    private javax.swing.JTextField txtConsName;
    private javax.swing.JTextField txtConsPhone;
    private javax.swing.JTextField txtRegStudentFN;
    private javax.swing.JTextField txtRegStudentId;
    private javax.swing.JTextField txtRegStudentName;
    private javax.swing.JTextField txtTSPId;
    private javax.swing.JTextField txtTSPLocation;
    private javax.swing.JTextField txtTSPName;
    private javax.swing.JTextField txtTSPNoLab;
    private javax.swing.JTextField txtTSPNoTeacher;
    private javax.swing.JTextField txtTSPStuCap;
    private javax.swing.JCheckBox wpsi;
    // End of variables declaration//GEN-END:variables
}
